version: '2'
services: 
  kafka:
    container_name: bds_kafka
    hostname: kafka
    image: "leophan/kafka-0-8:0.8.2.2"
    ports:
     - "2181:2181"
     - "9092:9092"
    environment:
      # KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_PORT: 9092
      KAFKA_CREATE_TOPICS: "bdslab:1:1"
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
    networks:
      - bds_network
  elasticsearch:
    container_name: bds_elasticsearch
    hostname: elasticsearch
    image: "leophan/elasticsearch-5:5.4.1"
    ports:
     - "9200:9200"
     - "9300:9300"
     - "5601:5601"

  spark-master:
    container_name: bds_spark_master
    image: leophan/spark-2:2.1.1
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    hostname: spark-master
    environment:
      MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: 127.0.0.1
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - /Users/leo/Zimportant/src/fastdata/target/scala-2.11:/conf
    networks:
      - bds_network

  spark-worker-1:
    container_name: bds_spark_worker
    image: leophan/spark-2:2.1.1
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker-1
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: 127.0.0.1
      SPARK_WORKER_CORES: 4
      SPARK_WORKER_MEMORY: 4g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    links:
      - spark-master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8081:8081
    volumes:
      - /Users/leo/Zimportant/src/fastdata/target/scala-2.11:/conf
    networks:
      - bds_network
  redis:
    container_name: bds_redis
    image: leophan/redis-3:3.2
    hostname: redis
    expose:
      - 6379
    ports:
      - 6379:6379