version: '3'
services: 
  fastdata:
    container_name: bds_fastdata
    hostname: localhost 
    image: "leophan/fastdata:0.1.1"
    ports:
     - "2181:2181"
     - "9092:9092"
     - "9090:9090"
     - "9200:9200"
     - "9300:9300"
     - "5601:5601"
     - "6379:6379"
    environment:
      # KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_PORT: 9092
      KAFKA_CREATE_TOPICS: "bdslab:1:1"
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
    volumes:
      - /Users/leo/Zimportant/src/fastdata/target/scala-2.11:/conf
    # networks:
    #   - bds_network
    network_mode: "bridge"
networks:
  bds_network: