package models

/**
  * Created by wilson on 7/2/17.
  */
object CassandraConstants {
  val ID = "id"
  val CLICK_ID = "click_id"
  val PRODUCT_ID = "product_id"
  val TIMESTAMP = "timestamp"
  val FP_ID = "fp_id"
  val LINK_ID = "link_id"
  val DNS_IP = "dns_ip"
  val PUBLIC_IP = "public_ip"
  val PRIVATE_IP = "private_ip"
  val REFERRER = "referrer"
  val USER_AGENT = "user_agent"
  val ISP = "isp"
  val COUNTRY = "country"
  val CITY = "city"
  val LANGUAGE = "language"
  val OS = "os"
  val BROWSER = "browser"
  val TIME_ZONE = "time_zone"
  val SCREEN_SIZE = "screen_size"
  val FONTS = "fonts"
  val HTTP_PARAMS = "http_params"
  val CAMPAIGN_ID = "campaign_id"
  val CHANNEL_ID = "channel_id"
  val ZONE_ID = "zone_id"
  val UTM_SOURCE = "utm_source"
  val UTM_CAMPAIGN = "utm_campaign"
  val UTM_MEDIUM = "utm_medium"
  val UTM_TERM = "utm_term"
  val NETWORK = "network"
  val FUTURE_PARAMS = "future_params"
  val USERNAME = "username"
  val LOGIN_TIME = "login_time"
  val LOGIN_IP = "login_ip"
  val LOGIN_TYPE = "login_type"
  val REGISTER_TIME = "register_time"
  val REGISTER_IP = "register_ip"
  val PAGE_URL ="page_url"
  val PAGE_TITLE ="page_title"
  val TIME_ON_SITE ="time_on_site"
  val PAGE_LOAD_TIME ="page_load_time"
  val REGISTER_TYPE ="register_type"
  val PHONE = "phone"
  val EMAIL = "email"
}
