package mapping

import java.util.UUID

import org.apache.spark.streaming.StreamingContext
import org.apache.spark.streaming.dstream.DStream

object Object {

  case class ESObj(msg: String)

  case class KafkaStreamObj(topics: String,
                            broker: String,
                            scc: StreamingContext)

  case class ElasticStreamObj(index: String,
                              _type: String,
                              dStream: DStream[AppObjOver])

  case class ElasticStreamJson(index: String,
                               _type: String,
                               dStream: DStream[String])

  case class AppObj(`@timestamp`: String,
                    `type`: String,
                    timestamp: String,
                    hostsource: String,
                    service: String,
                    remote_addr: String)

  case class AppObjOver(`@timestamp`: String,
                        `type`: String,
                        timestamp: String,
                        hostsource: String,
                        service: String,
                        remote_addr: String,
                        remote_user: String,
                        time_local: String,
                        status: String,
                        verb: String,
                        request: String,
                        bytes: String,
                        referrer: String,
                        agent: String,
                        xforwardedfor: String,
                        http_authorization: String,
                        a1: Int,
                        a2: Int,
                        a3: Int,
                        a4: Int,
                        a5: Int,
                        a6: Int,
                        a7: Int,
                        a8: Int
                       )

  case class ObjReceive(id: String,
                        click_id: String,
                        product_id: String,
                        timestamp: String,
                        link_id: String,
                        dns_ip: String,
                        public_ip: String,
                        private_ip: String,
                        referrer: String,
                        user_agent: String,
                        isp: String,
                        country: String,
                        city: String,
                        language: String,
                        os: String,
                        browser: String,
                        time_zone: String,
                        screen_size: String,
                        fonts: String,
                        http_params: String,
                        campaign_id: String,
                        channel_id: String,
                        zone_id: String,
                        utm_source: String,
                        utm_campaign: String,
                        utm_medium: String,
                        utm_term: String,
                        network: String,
                        future_params: String)

  case class Click(id: UUID,
                   click_id: UUID,
                   product_id: UUID,
                   timestamp: String,
                   link_id: UUID,
                   dns_ip: String,
                   public_ip: String,
                   private_ip: String,
                   referrer: String,
                   user_agent: String,
                   isp: String,
                   country: String,
                   city: String,
                   language: String,
                   os: String,
                   browser: String,
                   time_zone: String,
                   screen_size: String,
                   fonts: String,
                   http_params: String,
                   campaign_id: UUID,
                   channel_id: UUID,
                   zone_id: UUID,
                   utm_source: String,
                   utm_campaign: String,
                   utm_medium: String,
                   utm_term: String,
                   network: String,
                   future_params: String,
                   fp_id: UUID)

  case class ActiveUser(id: UUID,
                        click_id: UUID,
                        product_id: UUID,
                        timestamp: String,
                        link_id: UUID,
                        dns_ip: String,
                        public_ip: String,
                        private_ip: String,
                        referrer: String,
                        user_agent: String,
                        isp: String,
                        country: String,
                        city: String,
                        language: String,
                        os: String,
                        browser: String,
                        time_zone: String,
                        screen_size: String,
                        fonts: String,
                        http_params: String,
                        campaign_id: UUID,
                        channel_id: UUID,
                        zone_id: UUID,
                        utm_source: String,
                        utm_campaign: String,
                        utm_medium: String,
                        utm_term: String,
                        network: String,
                        future_params: String,
                        fp_id: UUID,
                        active: Int
                       )

  case class Visitor(id: String,
                     click_id: String,
                     product_id: String,
                     timestamp: String,
                     fp_id: String,
                     link_id: String,
                     dns_ip: String,
                     public_ip: String,
                     private_ip: String,
                     referrer: String,
                     user_agent: String,
                     isp: String,
                     country: String,
                     city: String,
                     language: String,
                     os: String,
                     browser: String,
                     time_zone: String,
                     screen_size: String,
                     fonts: String,
                     http_params: String,
                     campaign_id: String,
                     channel_id: String,
                     zone_id: String,
                     utm_source: String,
                     utm_campaign: String,
                     utm_medium: String,
                     utm_term: String,
                     network: String,
                     future_params: String,
                     username: String,
                     login_time: String,
                     login_ip: String,
                     login_type: String,
                     register_time: String,
                     register_ip: String,
                     page_url: String,
                     page_title: String,
                     time_on_site: String,
                     page_load_time: String,
                     register_type: String,
                     phone: String,
                     email: String)

}

